### ISSUE TITLE
System frameworks seem to be pointing to the wrong place when using Xcode 8

### ISSUE THREAD

**Issue by amotion** [jcampbell05/xcake#111]
When I add system frameworks to my Cakefile, they appear as red framework boxes in the project source tree.

I inspected the full path and noticed they are pointing to `/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/` but with Xcode 8 beta 6, that folder is actually in `iPhoneOS10.0.sdk`.

I've temporarily fixed it by adding an additional symlink that matches the name xcake is looking for, but am wondering if there's a config I'm missing?

**Comment by maximkhatskevich** [comment]
@amotion I guess this is something built-in (hardcoded?) into Xcake binary and we just need to add support for the latest Xcode version into Xcake itself. @jcampbell05 am I right? Can we make it dynamic somehow so Xcake always pick it up correctly from Xcode?

**Comment by jcampbell05** [comment]
@amotion @maximkhatskevich cc/@orta

This is actually handled by `xcodeproj`internally we use it's `add_system_framework` to add the frameworks to the target.

You can see the code here https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project/object/native_target.rb

It appears that it defaults to a internally hard coded path and version of the SDK or it uses the path provided by the `SDKROOT` configuration in your project. You can set the `SDKROOT` configuration to override this to point at the iOS 10 SDK.

You should be able to do this in Xcake like so:
`all_configurations.each { |c| c.settings["SDKROOT"] = "<SDK>"

Failing that updating the `xcodeproj` gem may get you a version with the internal version update to 10 (but its possible that the version hasn't been published yet due to Xcode 8 being in beta)

Potentially for Xcake we could look into if we could do some smarter herustics to determin the SDKROOT ourselves.  But may not be worth the effort since these major SDK releases only come around once a year so it should be managable for the few weeks before the Xcode 8 release.

**Comment by maximkhatskevich** [comment]
@jcampbell05 make sense. Keeping that in mind - it looks like no need to take any action on our side and try to invent a workaround inside Xcake to solve that temporary minor issue.

**Comment by amotion** [comment]
@jcampbell05 Thanks for the fast reply! I've added that config line but am still seeing references to the 9.3 folder in the project file:

```
		0CE1C6FC553278EBBA3C005C /* SystemConfiguration.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = SystemConfiguration.framework; path = Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/SystemConfiguration.framework; sourceTree = DEVELOPER_DIR; };
```

However, I do see that the SDKROOT flag was set in the build configuration section:

```
SDKROOT = "/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.0.sdk";
```

**Comment by amotion** [comment]
I've also tried using the latest `xcodeproj` from their `master` branch which looks like it tries to fix Xcode 8 issues. Will keep digging into it!

**Comment by jcampbell05** [comment]
@amotion  awesome! let me know if you find anything!

**Comment by chiahsien** [comment]
@amotion @jcampbell05 
Any update?
Xcode 8.0 + Xcake 0.7.1 still has this issue.

**Comment by chiahsien** [comment]
Besides frameworks, libraries point to MacOS sdk path, too.

**Comment by jcampbell05** [comment]
@chiahsien  could you tell me which `xcodeproj` you have ?

**Comment by chiahsien** [comment]
I've tried 1.3.3 and 1.4.1

1.3.3: wrong framework path, but the project file can be opened. 
1.4.1: correct framework path, but the project file can't be opened. The project file fails to be parsed.

**Comment by jcampbell05** [comment]
@chiahsien Could you upload a project that recreates the issue ? I'll look into whats change structure wise.

**Comment by chiahsien** [comment]
@jcampbell05 
Interesting, I can't reproduce it. :octocat: 
The frameworks path is correct, **but libraries path isn't.**

```
xcodeproj: 1.3.3
xcake: 0.7.1
```

Here's the sample project and Cakefile.
[XcakeTest.zip](https://github.com/jcampbell05/xcake/files/610458/XcakeTest.zip)

**Comment by jcampbell05** [comment]
@chiahsien is this still happening ? did Xcodeproj 1.4.X fix it ?

**Comment by chiahsien** [comment]
@jcampbell05 
xcake 0.8.8
xcodeproj 1.4.2
Both frameworks and libraries paths are wrong.
They all point to non-existing paths.

**Comment by jcampbell05** [comment]
Tried this on my machine and it seems to be okay with the latest Xcake on master and Xcodeproj. Your project file above compiles.

It may be worth filing this with Xcodeproj if you still have issues.
