### ISSUE TITLE
How to set complier flags for certain files?

### ISSUE THREAD

**Issue by chiahsien** [jcampbell05/xcake#123]
I've searched the docs and examples and issues, but can't find the answer.
I need to set compiler flags `-fno-objc-arc` to certain files, how can I do that?

**Comment by jcampbell05** [comment]
@chiahsien right now you can't since nobody has needed it. But I can implement it quickly, would something like this work ?

`target.include_files 'folder/file.c', '-fno-objc-arc'`

**Comment by divergio** [comment]
This is pretty old, but this is the way CocoaPods does it:
http://www.fabiancanas.com/blog/per-file-arc-in-cocoapods

The DSL doesn't support per-file exclusion, but supports it on a subspec level. 

This works fine for `-fno-objc-arc`, but maybe per-file compiler flags make sense because they can support any kind of flags (and it is supported in Xcode's interface).  

As an alternative to your proposal, maybe it could be something like `:flags => '-fno-objc-arc`? This is also kind of "Podfile style."

**Comment by chiahsien** [comment]
Awesome! 
I use Cocoapods too, so `target.include_files 'folder/file.c', :flags => '-fno-objc-arc'` looks good to me. 

One more thing, if I already include files via `folder/*.*`, would this make duplication?

**Comment by jcampbell05** [comment]
@chiahsien so my aim would be to avoid duplication, so Xcake tries to reduce your include / exclude statements down to the minimum needed to represent what you define in your `Cakefile`

So in your case if a file is included twice once with a flag and once with, I aim to make it de-duplicate and include the flag. That way doing this would work:

```
target.include_files 'folder/*.*'
target.include_files 'folder/file.c`, :flags => '-fno-objc-arc'
```

**Comment by divergio** [comment]
Thinking of edge cases, here, what about multiple flags and multiple declarations?

```
target.include_files 'folder/*.*', :flags => '-flag_a'
target.include_files 'folder/file.c', :flags => '-flag_b'
target.incldue_files 'folder/file.*', :flags => 'flag_c'
```

Is it "de-duplicate and append flag"? 
In which case, `file.c` gets `:flags => '-flag_a -flag_b -flag_c'?

I think that _should_ work.

**Comment by chiahsien** [comment]
Current syntax for `include_files` is to use `= ["..."]` and `<< "..."`, so are you going to change the syntax?

**Comment by jcampbell05** [comment]
@chiahsien @divergio Good points.

If I was to change how `include_files` worked then I think `<<` would no longer work at least if you needed `:flags` and calling `include_files` would emulate `<<` since it  would just add it to the internal array of files to add.

I could always have a new `add_flag` or `remove_flag` method ?

**Comment by chiahsien** [comment]
@jcampbell05 
I don't think `remove_flag` method necessary, because files have no flag by default, right?
Maybe a new method called `set_files` and looks like this:
`target.set_files ['folder1/*.m, folder2/*.c'], :flags => ['-flag_a, -flag_b']`

(I don't write ruby, forgive me if the syntax isn't correct)

**Comment by chiahsien** [comment]
@jcampbell05 any progress about this feature request?

**Comment by jcampbell05** [comment]
@chiahsien I've started a spike to look into this :), just figuring out what changes are needed.

**Comment by jcampbell05** [comment]
So its quite a bit of work due to Xcake's architecture but we are working on adding it to Struct https://github.com/lyptt/struct
