### ISSUE TITLE
How to include plist file properly?

### ISSUE THREAD

**Issue by chiahsien** [jcampbell05/xcake#125]
In order to show the `plist` file in left project navigator, the target has to include it.
`target.include_files << "MyApp/*.plist"`

But if I do so, the `plist` file will be added to `Copy Bundle Resources` build phase, and Xcode will show a warning:
`Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'MyApp/MyApp-Info.plist'.`

So, my question is: how to show the plist file in project navigator (so that I can open it in Xcode) and not add to Copy Bundle Resources build phase?

**Comment by jcampbell05** [comment]
I'll have a think on how we can do this in Xcake, how would you expect this to be done ?

**Comment by chiahsien** [comment]
Maybe Xcake can check the file extension, if it's `plist` then not adding to Copy Bundle Resources build phase?

So `target.include_files << "MyApp/*.plist"` doesn't need to change.

**Comment by maximkhatskevich** [comment]
@chiahsien we can not ignore file to include just because it has "plist" extension, it's up to developer what to include in the project and plists are often used for many different purposes - from pre-populating database with default data to providing specific settings in run time. I'm sure you mean the "Info file" (a special file with special properties for a target, that is required by Xcode) which is a plist file too. It's absolutely useless feature to be able to add the "Info" file into project navigator, because you have access to that file via standard Xcode interface when click on your project file, then select the needed target and then switch to "Info" tab in the main Xcode pane. I hope it makes sense for you?! Just make sure the info file is stored outside of the folder with all source code files, as I described here:
https://github.com/jcampbell05/xcake/blob/master/example/app/Cakefile#L180
https://github.com/jcampbell05/xcake/blob/master/example/app/Cakefile#L184

I think this issue should be closed.
