### ISSUE TITLE
Add possibility to create aggregate targets

### ISSUE THREAD

**Issue by 0111b** [jcampbell05/xcake#58]

**Comment by jcampbell05** [comment]
Thanks for your issue @0111b  I'm always open to Pull Requests but I'll look into seeing if we can get this in for you. Whats your paticular use case ?

**Comment by jcampbell05** [comment]
Should be implementing this into 0.7 requires a bit of work to add a special target type in Xcake.

**Comment by maximkhatskevich** [comment]
@jcampbell05 What does it mean "aggregate targets"? Just wondering :)

**Comment by jcampbell05** [comment]
@maximkhatskevich It's a special target type in Xcode whose sole purpose is just to let you configure multiple targets to built at once. 

So Aggregate Target C could be configured to trigger target A and B to be built at the same time :) Which can be cleaner than making Target A a dependency of B since A may not be related to B (i.e if you're building a multi-platform app and you have a OS X and iOS Target)

**Comment by maximkhatskevich** [comment]
Interesting. Never heard of that. Something new to Xcode 8 which I missed? Anyway, I'll google it. Thanks!

**Comment by jcampbell05** [comment]
@maximkhatskevich been around a while just not used that often unless you build libraries.
