### ISSUE TITLE
all_configuration.each doesn't seem to work

### ISSUE THREAD

**Issue by brennantaylor** [jcampbell05/xcake#82]
The following doesn't seem to set the bridging header in the project file.

```text
target.all_configurations.each { |c| c.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "Other Sources/My-Bridging-Header.h"}
```

**Comment by brennantaylor** [comment]
It doesn't write `SWIFT_OBJC_BRIDGING_HEADER` anywhere in the project file in fact.

**Comment by brennantaylor** [comment]
This works:

```text
    target.debug_configuration.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "Other Sources/ExpediaBookings-Bridging-Header.h"
    target.release_configuration.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "Other Sources/ExpediaBookings-Bridging-Header.h"
```

**Comment by jcampbell05** [comment]
@brennantaylor  Do you have an example project for this  bug?

**Comment by maximkhatskevich** [comment]
@brennantaylor take a look on my comments for this issue https://github.com/jcampbell05/xcake/issues/78 I think that's related. Basically you should access specific configurations inside the

`target.all_configurations.each do |configuration|`

loop by using

`if configuration.name == 'MyConfiguration1' do <put_target_specific_settigns_here> end`

Hope that makes sense.

@jcampbell05 I should have time early next week to update documentation and provide comprehensive example Cakefile, as I promised. This would help resolve several issues that are currently opened. Sorry I still wasn't able to do so, still super busy/stressed at work yet.

**Comment by jcampbell05** [comment]
@maximkhatskevich No problem, I'm the same. Sorry for not fixing these issues as well :)

**Comment by brennantaylor** [comment]
The example project is the auto generated project with `xcake init`.

**Comment by jcampbell05** [comment]
Cheers! I'm taking a look

**Comment by jcampbell05** [comment]
@maximkhatskevich @brennantaylor  I think I have discovered the issue for this

Basically the `all_configurations` returns all of the configurations created at that moment. The bug is caused by implicit configurations.

When your Cakefile doesn't specify any configurations we automatically generate the Debug and Release Configurations as sensible defaults. 

However these are generated later on in the process of creating your project file so `all_configurations` actually returns no configurations.

So one solution is to use to methods you are using above and then `all_configurations` should return them since those methods will also create a configuration.

I will push a patch to get Xcake to create the configurations a little earlier :)

**Comment by maximkhatskevich** [comment]
Sure thing, I didn't mention, but before access configurations inside target definition, I have explicit list of all configurations on project level like this:

`project.debug_configuration :Debug`
`project.release_configuration :Staging`
`project.release_configuration :RC`
`project.release_configuration :Production`
`project.release_configuration :AppStore`
