### ISSUE TITLE
Defining framework with public headers

### ISSUE THREAD

**Issue by dchohfi** [jcampbell05/xcake#98]
Hey guys, first of all: congratulations! This is an awesome project and have lots of potencial. Thank you for starting and maintaining that.

Right now I can create targets for watch, today extension and a shared common framework, the only problem that I'm facing is how to set those headers on the framework to be access publicly on those targets?

Tried to find a solution on Xcodeproj repo but couldn't get an answer.
https://github.com/CocoaPods/Xcodeproj/issues/222

**Comment by jcampbell05** [comment]
@dchohfi Thank you for the kind words, so right now this is something I'm still trying to figure out.

In the current version of Xcake in `master` any headers will automatically be added a Headers Build Phases. The version on RubyGems currently lacks this functionality.

However I still need to figure out how to add some granularity to this system. People writing Apps won't want their Headers being shared and those writing Libraries will only want a few select Headers to be shared.

I think the best way is for Xcake to add the Headers to the project and allow you to turn on or off us automatically adding a build phase for you so that you have to explicity declare the build phase for them.

**Comment by jcampbell05** [comment]
@dchohfi  so an update on this, I have started a branch which will allow you to specify this.

**Comment by jcampbell05** [comment]
@dchohfi I have released v0.8.0 which should have this functionaliy in.
